# Generated by Django 4.2.30 on 2026-04-29 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Atlas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(blank=True, default="", max_length=100)),
                (
                    "dishes",
                    models.BooleanField(
                        choices=[(0, "Italy"), (1, "India"), (2, "China")],
                        default="python",
                        max_length=100,
                    ),
                ),
            ],
        ),
    ]
