# Generated by Django 4.2.30 on 2026-05-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="atlas",
            options={"ordering": ["created"]},
        ),
        migrations.AlterField(
            model_name="atlas",
            name="dishes",
            field=models.IntegerField(
                choices=[(0, "Italy"), (1, "India"), (2, "China")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="atlas",
            name="highlighted",
            field=models.TextField(blank=True),
        ),
    ]
