# Generated by Django 4.2.30 on 2026-05-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0002_alter_atlas_options_alter_atlas_dishes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="atlas",
            name="dishes",
        ),
        migrations.AddField(
            model_name="atlas",
            name="country",
            field=models.CharField(
                choices=[
                    ("Italy", "Italy"),
                    ("India", "India"),
                    ("China", "China"),
                    ("France", "France"),
                    ("Japan", "Japan"),
                    ("Mexico", "Mexico"),
                    ("Thailand", "Thailand"),
                    ("Greece", "Greece"),
                    ("Spain", "Spain"),
                    ("Turkey", "Turkey"),
                ],
                default="Italy",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="atlas",
            name="cuisine",
            field=models.CharField(default="Italian", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="atlas",
            name="dish",
            field=models.CharField(default="Spaghetti", max_length=200),
            preserve_default=False,
        ),
    ]
