# Generated by Django 4.2.30 on 2026-05-12 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("atlas", "0003_remove_atlas_dishes_atlas_country_atlas_cuisine_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("Italy", "Italy"),
                            ("India", "India"),
                            ("China", "China"),
                            ("France", "France"),
                            ("Japan", "Japan"),
                            ("Mexico", "Mexico"),
                            ("Thailand", "Thailand"),
                            ("Greece", "Greece"),
                            ("Spain", "Spain"),
                            ("Turkey", "Turkey"),
                        ],
                        max_length=100,
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("cuisine_type", models.CharField(max_length=100)),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restaurants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-rating", "name"],
            },
        ),
        migrations.AddField(
            model_name="atlas",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dishes",
                to="atlas.restaurant",
            ),
        ),
    ]
