# Generated by Django 4.2.30 on 2026-05-15 14:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("atlas", "0004_restaurant_atlas_restaurant"),
    ]

    operations = [
        migrations.AddField(
            model_name="atlas",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_atlas", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
